name: server

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build server --tag yuna:latest
    - name: Test Docker container
      run: docker run yuna:latest make test
